[tool.isort]
profile = "black"
line_length = 80

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
exclude = [".git", "**/__pycache__", "**/migrations"]

[tool.django-stubs]
django_settings_module = "tests.settings"

[tool.black]
line-length = 80
target-version = ['py310']

exclude = '''
    /(
    __pycache__
  | migrations
    )/
  '''
