[tool.isort]
profile = "black"
line_length = 80

[tool.pyright]
exclude = [".git", "**/__pycache__", "**/migrations"]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "tests.settings"

[tool.black]
line-length = 80
target-version = ['py39']

exclude = '''
    /(
    __pycache__
  | migrations
    )/
  '''
