# Generated by Django 4.0.2 on 2022-02-27 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferredSolution',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(db_index=True, max_length=32)),
                ('solution_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StoredTriplet',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=32)),
                ('verb', models.CharField(max_length=32)),
                ('obj', models.CharField(max_length=32)),
                ('is_inferred', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='storedtriplet',
            index=models.Index(fields=['verb'], name='triplets_st_verb_382573_idx'),
        ),
        migrations.AddIndex(
            model_name='storedtriplet',
            index=models.Index(fields=['subject', 'verb'], name='triplets_st_subject_a1548a_idx'),
        ),
        migrations.AddIndex(
            model_name='storedtriplet',
            index=models.Index(fields=['verb', 'obj'], name='triplets_st_verb_f66ec2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storedtriplet',
            unique_together={('subject', 'verb', 'obj')},
        ),
        migrations.AddField(
            model_name='inferredsolution',
            name='inferred_triplet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inferred_by', to='triplets.storedtriplet'),
        ),
        migrations.AlterUniqueTogether(
            name='inferredsolution',
            unique_together={('rule_id', 'solution_hash')},
        ),
    ]
