# Generated by Django 4.0.3 on 2022-03-07 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoredFact',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=64)),
                ('verb', models.CharField(max_length=64)),
                ('obj_str', models.CharField(max_length=64, null=True)),
                ('obj_int', models.IntegerField(null=True)),
                ('is_inferred', models.BooleanField()),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_facts', to='triplets.transaction')),
                ('removed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_facts', to='triplets.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InferredSolution',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('inferred_fact_hash', models.CharField(max_length=32)),
                ('rule_id', models.CharField(max_length=32)),
                ('solution_hash', models.CharField(max_length=64)),
                ('inferred_fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inferred_by', to='triplets.storedfact')),
            ],
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['subject', 'verb', 'obj_str'], name='triplets_st_subject_5a65b7_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['subject', 'verb', 'obj_int'], name='triplets_st_subject_e3e2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['added', 'removed'], name='triplets_st_added_i_fae311_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['verb'], name='triplets_st_verb_a37009_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['subject', 'verb'], name='triplets_st_subject_62ab31_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['verb', 'obj_str'], name='triplets_st_verb_2f0310_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['verb', 'obj_int'], name='triplets_st_verb_4e2b3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storedfact',
            unique_together={('subject', 'verb', 'obj_str', 'obj_int', 'removed')},
        ),
        migrations.AddIndex(
            model_name='inferredsolution',
            index=models.Index(fields=['rule_id'], name='triplets_in_rule_id_868fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='inferredsolution',
            index=models.Index(fields=['rule_id', 'solution_hash', 'inferred_fact_hash'], name='triplets_in_rule_id_b8ae46_idx'),
        ),
    ]
