# Generated by Django 4.0.3 on 2022-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfact',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['entity', 'attr', 'value_float'], name='triplets_st_entity_ca7195_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfact',
            index=models.Index(fields=['attr', 'value_float'], name='triplets_st_attr_8f4c52_idx'),
        ),
    ]
