name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Get python ready
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        make install
    - name: Run Tests
      run: |
        make coverage
